name: Database Migration

on:
  push:
    branches: [main]

jobs:
  migrate_database:
    runs-on: ubuntu-latest
    name: Run Sequelize Migration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        # Kita perlu install dependencies agar sequelize-cli bisa jalan
        run: npm ci

      - name: Run Sequelize Migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
        run: npx sequelize-cli db:migrate

      - name: Clean Nuxt Auto-Config
        run: rm -f .output/server/wrangler.json || true

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .output/public --project-name=nyawitai
